# -*- coding: utf-8 -*-
"""argparse.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_lO--pLTloLh7VgX70ide-qCctu5Iye7
"""

#!/usr/bin/env python
"""Chucky needs help!
As punishment for his multitudinous trangressions Chucky's mom
often demands that he writes bizzarely archaic normative statements
hundreds of times so that he learns his lesson. 
The problem is Chucky's mom never tells him how many times he
needs to write these statements, or what the name of the file
(that he should write these statements in) is.
This time, Chucky ate ALL the cookies and he will be punished.
Let's help him by writing a script that takes two command
line inputs:
 -- An integer representing the amount of times Chucky must write the statement.
 -- The path to the file that Chucky should write the statement to.
Chucky already got started on the script, but let's finish it for him.
"""

#1. import package
import argparse

def main(args):
  print(args)
    statement = "Thou shall not eat all the cookies."
    with open(args.output_path, "w") as sink:
        for _ in range(args.num):
            print(statement, file=sink)

#step 2: fill this out
if __name__ == "__main__":
    parser = argparse.ArgumentParser()                            #ArgumentParser contains the methods we can use
    parser.add_argument("num", help="give me an integer number")  #adds arguments to parser
    parser.add_argument("--output-path", required = True, help="path to write the file to")            #add another argument for pathway
    main(parser.parse_args())